Add optional :meta field
SparkHub/shortener pull request #2
Opened 2016-10-20 20:50 UTC by mchaisse

2016-10-21 20:46 UTC, ghost requested changes
minimal change

2016-10-21 20:46 UTC, ghost commented on app/models/shortener/shortened_url.rb
>        scope = owner ? owner.shortened_urls : self
Move this to `apply_scope`

2016-10-21 20:51 UTC, epmwgs commented on app/models/shortener/shortened_url.rb
> +                     expires_at: nil, fresh: false, meta: nil)
Instead of 'fresh', how about 'force' ?

2016-10-24 21:24 UTC, mchaisse commented on app/models/shortener/shortened_url.rb
> +                     expires_at: nil, fresh: false, meta: nil)
Since it is already part of the gem, we can open a new ticket to change the name.

2016-10-24 22:30 UTC, mchaisse commented
@epmwgs PTAL

2016-10-24 22:31 UTC, ghost approved these changes

2016-10-24 22:33 UTC, merged