[HPARK-294] - Add additional columns
SparkHub/shortener pull request #6
Opened 2017-01-25 23:26 UTC by evaldez-gs

**Changes:**

- Add 3 new columns: message_id (uuid), source (string) and campaign_user_id (uuid)
- Change main migration to consider last changes
- Change `short_url`, `generate` and `generate!` methods to support new optional columns
- Add changes to README.md (includes an additional migration to work)
- Add unit tests
- Update rspec version to run specs
- Update gem version to highlight new changes

2017-01-25 23:40 UTC, ghost approved these changes

2017-01-26 00:18 UTC, mchaisse requested changes
+ fix tests + what we talked about 😉

2017-01-26 00:18 UTC, mchaisse commented on README.rdoc
> +      add_column :shortened_urls, :source, :string, limit: 50
Looking at the `migration.rb` file, `source` has an index, which is missing here.

2017-01-26 00:18 UTC, mchaisse commented on lib/shortener/version.rb
> +  VERSION = '1.0.3'
Don't tag yet, this will be done during bump version process after merge.

2017-01-28 00:34 UTC, evaldez-gs commented
New changes:

- Change naming to be more generic for new columns
- Reuse owner column
- Change engine to postgresql to use `uuid` and `hstore`
- Change unit tests
- Update documentation

2017-01-30 22:49 UTC, evaldez-gs commented
@mchaisse I've changed it according to new changes listed in previous comment and last discussion about `travis`. Could you review it? Thanks!

2017-01-30 23:29 UTC, mchaisse commented on README.rdoc
> +Tested RVM versions: +2.2.3+ and +2.3.1+
This section is part of `Ruby Version Support`

2017-01-30 23:29 UTC, mchaisse commented on app/helpers/shortener/shortener_helper.rb
> +                                                 source_type:     source_type)
too many spaces or align with the other parameters

2017-01-30 23:29 UTC, mchaisse commented on spec/dummy/config/database.yml
> +  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
Prefer single quotes `'` if no interpolation.

2017-01-30 23:29 UTC, mchaisse commented on spec/dummy/config/database.yml
> +  database: <%= ENV.fetch("DB_NAME") { 'shortener_test' } %>
same

2017-01-30 23:59 UTC, evaldez-gs commented on README.rdoc
> +Tested RVM versions: +2.2.3+ and +2.3.1+
The comment is inside that section :)

2017-01-31 00:00 UTC, evaldez-gs commented
I've fixed last changes as requested, just I didn't know what to change on README.md.

2017-01-31 00:24 UTC, mchaisse commented on README.rdoc
> +Tested RVM versions: +2.2.3+ and +2.3.1+
👍

2017-01-31 00:24 UTC, mchaisse approved these changes
LGTM

2017-01-31 00:25 UTC, merged